<a href="https://colab.research.google.com/github/D-Lakshmi-Priya/numpy/blob/main/Introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install numpy

In [ ]:
import numpy as np

In [ ]:
# Create a numpy array
# 1D array

arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [ ]:
# Creating 2D array - Matrix
arr2D = np.array([
[1,2,3],[4,5,6]
])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Creating arrays with default values

# Creating Matrix with all values of elements as '0'
allZeros = np.zeros((2,3))
print(allZeros)

# Creating Matrix with all values of elements as '1'
allOnes = np.ones((2,3))
print(allOnes)

# Creating Matrix with all values of elements as 'Constant values - n ~ Fill value'
allConstant = np.full((2,3),6)
print(allConstant)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [ ]:
# Create an Identity Matrix - I

identity = np.eye(4)
print(identity)

# Indentity Matrix - Aii = 1 && Aij = 0
# For all A Belongs to R MxN
# Aij -

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Creating random Matrices

# with 0 & 1
rand1 = np.random.rand(3,3)
print(rand1)

# between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.0235254  0.13149137 0.80879369]
 [0.70545253 0.58427955 0.75269686]
 [0.22489789 0.08784027 0.56375555]]
[[10 16 14]
 [15 14 11]
 [13 18 16]]


In [ ]:
# Array Properties
arr = np.array([[1,2,3,4],[3,4,5,6]])
print(arr)

# Shape of array
print(f'\nThe shape of the array is {arr.shape}')

# Size of array
print(f'The size of the array is {arr.size}')

# Datatype of array
print(f'The Data type of the array is {arr.dtype}')

# Dimensions of array
print(f'The Dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [3 4 5 6]]

The shape of the array is (2, 4)
The size of the array is 8
The Data type of the array is int64
The Dimension of the array is 2


In [ ]:
# Indexing and Slicing

# Access the elements in ID Array

arr = np.array([1,2,3,8])
print(arr)
print(arr[2])

# Slicing the elements

print(arr[0:3])

# Access the elements in 2D Array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2[1,2])

 # first row with all columns
print(arr2[0,:])

# first column with all rows
print(arr2[:,0])

[1 2 3 8]
3
[1 2 3]
[[1 2 3]
 [4 5 6]]
6
[1 2 3]
[1 4]


In [ ]:
#l1 =[]
#[l1.append(_) for _ in range(10)]

#print(l1)


l1 = np.arange(0,10)

print(l1)

l2 = np.arange(10,-0,-3)
print(l2)

[0 1 2 3 4 5 6 7 8 9]
[10  7  4  1]


In [ ]:
# Mathmatical operations

a = np.array([1,2,3])
b = np.array([4,5,6])

print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is [5 7 9]
The diff of a and b is [-3 -3 -3]
The product of a and b is [ 4 10 18]
The division of a and b is [0.25 0.4  0.5 ]


In [ ]:
# Matrix multiplication
b1 = np.array([[1,2,3],[4,5,6]])
b2 = np.array([[5,6],[7,8],[1,3]])

# Dot product  ---- product = AB -- A m x n -- B n x p
c = np.dot(b1,b2)
print(c)

[[22 31]
 [61 82]]


In [ ]:
print(b1)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]
